# Generated by Django 3.1.7 on 2023-08-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='new.app1_company',
        ),
    ]
