# Generated by Django 3.1.7 on 2023-08-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230824_1210'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='new.app1_employee',
        ),
    ]
