# Generated by Django 4.2.3 on 2023-09-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_auto_20230824_1223"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arthematics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_1", models.FloatField()),
                ("number_2", models.FloatField()),
                ("date_1", models.DateTimeField(auto_now_add=True)),
                (
                    "choicefield",
                    models.CharField(
                        choices=[
                            ("ADD", "ADD"),
                            ("SUB", "SUB"),
                            ("MUL", "MUL"),
                            ("DIV", "DIV"),
                        ],
                        max_length=200,
                    ),
                ),
                ("result", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
